#' scRecoverTest: A test dataset for scRecover
#'
#' A test dataset containing a single-cell RNA-seq (scRNA-seq) read counts matrix and its cell type information.
#'
#' \itemize{
#'   \item counts. A matrix of raw read counts of scRNA-seq data which has 200 genes (rows) and 150 cells (columns).
#'   \item labels. A vector of integer specifying the two cell types in \code{counts}. Also could be generated by: \code{labels <- c(rep(1,50), rep(2,100))}.
#' }
#'
#' @name scRecoverTest
#' @aliases counts labels
#' @docType data
#' @keywords data
#' @usage data(scRecoverTest)
#' @format
#' \itemize{
#'   \item counts. A non-negative integer matrix of scRNA-seq raw read counts, rows are genes and columns are cells.
#'   \item labels. A vector of integer specifying the cell types in the read counts matrix, corresponding to the columns of \code{counts}.
#' }
#' @source Petropoulos S, et al. Cell, 2016, 165(4): 1012-1026.
#' @seealso
#' \code{\link{scRecover}}, for the imputation of single-cell RNA-seq data.
#'
#' @examples
#' # Load test data for scRecover
#' data(scRecoverTest)
#'
#' # Run scRecover with Kcluster specified
#' scRecover(counts = counts, Kcluster = 2)
#'
#' # Run scRecover with labels specified
#' scRecover(counts = counts, labels = labels)
#'
NULL




